# Generated by Django 4.2.11 on 2026-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('pago_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagamentos',
                'ordering': ['-mes'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('frequencia', models.CharField(blank=True, default='Ilimitado', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cor', models.CharField(default='#2979FF', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planos',
                'ordering': ['nome'],
            },
        ),
    ]
