# Generated by Django 4.2.11 on 2026-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkins',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('hora', models.TimeField()),
                ('vagas', models.PositiveIntegerField(default=12)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'horario_templates',
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('dia_semana', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('vagas', models.PositiveIntegerField(default=12)),
            ],
            options={
                'db_table': 'horarios',
                'ordering': ['data', 'hora'],
                'unique_together': {('data', 'hora')},
            },
        ),
    ]
